# -*- coding: utf-8 -*-
{
    'name': 'FedEx REST - Label References',
    'version': '16.0.1.0.0',
    'category': 'Inventory/Delivery',
    'summary': 'Add customer reference fields to FedEx REST shipping labels',
    'description': """
Adds customer reference fields (PO Number, Customer Reference, Invoice Number)
to FedEx labels generated by the delivery_fedex_rest module.

This fixes a regression where the newer REST-based FedEx integration does not
populate the reference fields on labels that the legacy SOAP-based module
(delivery_fedex) handled automatically.

References are sourced from:
- Customer Reference: Sale Order name (picking origin)
- PO Number: Customer Reference field on the Sale Order (client_order_ref)
- Invoice Number: Sale Order name
""",
    'author': 'OSI',
    'website': 'https://opensourceintegrators.com',
    'depends': ['delivery_fedex_rest'],
    'data': [],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
